/** Advanced Transform UI models (Safe Expression Engine; no AI). */

export type MappingMode = 'basic_jsonpath' | 'full_event_jsonata' | 'full_event_regex'

export type TransformPreviewStage = 'mapping' | 'enrichment'

export type AdvancedTransformUiMode = 'advanced' | 'expert'

export type AdvancedTransformEngineMode = 'jsonata' | 'regex_extract'

export type AdvancedTransformRuleDraft = {
  id: string
  uiMode: AdvancedTransformUiMode
  outputField: string
  mode: AdvancedTransformEngineMode
  expression: string
  sourcePath: string
  pattern: string
  group: number
  defaultValue: string
  ruleId: string
}

export function newAdvancedTransformRuleId(): string {
  return `at-${Date.now().toString(36)}-${Math.random().toString(16).slice(2, 6)}`
}

export function defaultAdvancedRule(uiMode: AdvancedTransformUiMode): AdvancedTransformRuleDraft {
  return {
    id: newAdvancedTransformRuleId(),
    uiMode,
    outputField: '',
    mode: uiMode === 'expert' ? 'regex_extract' : 'jsonata',
    expression: '',
    sourcePath: '$.message',
    pattern: '',
    group: 1,
    defaultValue: '',
    ruleId: '',
  }
}

export const FULL_EVENT_JSONATA_GUIDANCE = [
  'Transform the entire event using JSONata.',
  'Paste a JSONata expression that returns the final event object.',
  'JSONata can create, rename, remove, combine, and normalize fields.',
] as const

export const FULL_EVENT_REGEX_GUIDANCE = [
  'Paste a complete Regex transform config generated by an external tool, preview it against the source event, then save it.',
  'Use a JSON object with preserve_source and rules (output_field, source_path, pattern, group, default).',
  'Preview applies all rules at once; save is enabled only after a successful preview.',
] as const

/** Re-export Timestamp → UTC Transform UX constants for callers that already import this module. */
export {
  TIMESTAMP_UTC_AFFORDANCE_LABEL,
  TIMESTAMP_UTC_JSONATA_GUIDANCE,
  TIMESTAMP_UTC_REGEX_LIMITATION_GUIDANCE,
} from '../utils/timestampUtcTransformTemplate'
